name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Измените на имя вашей основной ветки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker build -t huveid/nginxcicd -f Dockerfile .
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push huveid/nginxcicd 
