name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Generate timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%S')"

    - name: Build Docker image
      run: |
        timestamp=$(echo "${{ steps.timestamp.outputs.timestamp }}")
        docker build -t huveid/nginxcicd:${timestamp} -f Dockerfile .
      env:
        DOCKER_BUILDKIT: 1

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        timestamp=$(echo "${{ steps.timestamp.outputs.timestamp }}")
        docker push huveid/nginxcicd:${timestamp}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get timestamp from previous job
      id: timestamp
      run: echo "::set-output name=timestamp::${{ needs.build.outputs.timestamp }}"

    - name: Pull Docker image from Docker Hub
      run: |
        timestamp=$(echo "${{ steps.timestamp.outputs.timestamp }}")
        docker pull huveid/nginxcicd:latest

    - name: Run Docker container
      run: |
        docker run -d -p 80:80 huveid/nginxcicd:latest --restart=always -t umedsimage

    - name: Docker ps
      run: docker ps -a
    - name: Docker Container Logs
      run: docker logs umedsimage

    - name: NGINX Error Log
      run: docker exec umedsimage cat /var/log/nginx/error.log

